services:
  postgres:
    image: postgres:15
    container_name: hair_salon_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app_network

  postgres_test:
    image: postgres:15
    container_name: hair_salon_test_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    ports:
      - "${POSTGRES_PORT_TEST}:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
